# Generated by Django 4.1.1 on 2022-09-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('StudId', models.AutoField(primary_key=True, serialize=False)),
                ('StudName', models.CharField(max_length=140)),
                ('Course', models.CharField(max_length=140)),
                ('Rating', models.IntegerField()),
            ],
            options={
                'ordering': ['StudId'],
            },
        ),
    ]
