# Generated by Django 4.1.1 on 2022-09-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['StudId']},
        ),
    ]
