FROM python:3.9-slim-buster
WORKDIR /app
RUN pip install --upgrade pip
COPY . /app
RUN pip install -r requirements.txt; \
    python manage.py makemigrations; \
    python manage.py migrate;
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]